version: "3"
services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge